### ISSUE TITLE
页面滚动时候对话框跟着滚动

### ISSUE THREAD

**Issue by zhetengbiji** [pillys/vdialog#1]
普通解决方式： .vdialog{position: fixed;}

**Comment by pillys** [comment]
实际应用中是有这样的场景需要，在接下来的版本中会添加对 fixed 的支持，赞一个，感谢

**Comment by pillys** [comment]
感谢您的建议，该功能已随 v1.1 版本发布。
see：http://www.qque.com/vDialog/changes.html
