### ISSUE TITLE
与自己样式表冲突

### ISSUE THREAD

**Issue by gitdust** [pillys/vdialog#2]
自己已经为整个网站布局写了样式
引用vDialog样式之后，冲突很明显，Dialog布局严重变形
我又不可能去一一查找冲突的样式，太浪费时间了

**Comment by pillys** [comment]
可否给出一个地址，我来看一下问题所在，以便尽快修复，谢谢。

**Comment by gitdust** [comment]
是个demo，可能无法上线，没有借用任何框架UI，也许是我命名跟你们的样式重复了或者优先级高了。
我的建议是你们的样式命名统一一个你们项目的前缀。
